# Design
set ::env(DESIGN_NAME) "top"

# Sources
set ::env(VERILOG_FILES) [list \
    "$::env(DESIGN_DIR)/../src/top.v" \
    "$::env(DESIGN_DIR)/../src/stubs.v" \
]

# Clock
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) 10.0

# Floorplanning
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 1000 1000"
set ::env(PL_TARGET_DENSITY_PCT) 30

# Macro Placement (Generated by your python script)
set ::env(MACRO_PLACEMENT_CFG) "$::env(DESIGN_DIR)/macro_placement.cfg"

# Routing
set ::env(RT_MAX_LAYER) "met4"

# ---------------------------------------------------------
# POWER DISTRIBUTION NETWORK (PDN) FIX
# ---------------------------------------------------------

# 1. Define the names of the power/ground nets in your Verilog
set ::env(VDD_NETS) [list vccd1 vdda1]
set ::env(GND_NETS) [list vssd1 vssa1]

# 2. Connect the "1.8V" and "Ground" constants to these nets
set ::env(VDD_PIN) "vccd1"
set ::env(GND_PIN) "vssd1"

# 3. DISABLE Core Rings and Rails
# We rely on the Pad Frame for power. We don't need a core grid for this demo.
set ::env(FP_PDN_CORE_RING) 0
set ::env(FP_PDN_ENABLE_RAILS) 0 

# 4. Disable Strict Checking
# This stops the "[PDN-0189] Supply pin ... not connected" errors
# caused by the missing .lib files.
set ::env(FP_PDN_CHECK_NODES) 0

# ---------------------------------------------------------
# LIBRARIES
# ---------------------------------------------------------

set IO_ROOT "/Users/refikyalcin/.volare/volare/sky130/versions/0fe599b2afb6708d281543108caf8310912f54af/sky130A/libs.ref/sky130_fd_io"

# 1. PHYSICAL VIEWS (LEF) - KEEP THESE
set ::env(EXTRA_LEFS) [list \
    "$IO_ROOT/lef/sky130_fd_io.lef" \
    "$IO_ROOT/lef/sky130_ef_io.lef" \
]

# 2. TIMING/LOGIC VIEWS (LIB) - DISABLED
# set ::env(EXTRA_LIBS) ...

# Linter Settings
set ::env(RUN_LINTER) 1
set ::env(ERROR_ON_LINTER_ERRORS) 0